### ISSUE TITLE
Swap partition ;D

### ISSUE THREAD

**Issue by RENANZG** [aomgiwjc/Unix-Bootstrap-Installs#1]
**NOOB HERE**

I'm learning how to use linux. I really liked your tutorial (Debian 11.5 BTRFS and Luks Encryption Installation | Command Line Install), I tried to apply it in Debian Bookworm.

(I use Sd Card with MicroSDXC adapter or a USB adapter. It works like the keys to a car.)

Now, my partitions look like this:
```
NAME          MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
sda             8:0    1   480M  0 disk  
├─sda1          8:1    1   100M  0 part  /boot/efi
└─sda2          8:2    1   378M  0 part  /boot
nvme0n1       259:0    0 238,5G  0 disk  
├─nvme0n1p1   259:1    0    32G  0 part  
│ └─cryptroot 254:0    0    32G  0 crypt /home
│                                        /.snapshots
│                                        /
└─nvme0n1p2   259:2    0     8G  0 part  
  └─cryptswap 254:1    0     8G  0 crypt [SWAP]
```
![screen-2023-07-07-09-04-30](https://github.com/aomgiwjc/Unix-Bootstrap-Installs/assets/53377291/933e38b4-a115-4459-8a42-228fdd94e2f7)

I think the problem is that Swap didn't activate at startup. So I tried manually:

```
root@debian:~# swapon -a
swapon: /dev/nvme0n1p2: read swap header failed
```
```
root@debian:~# sudo journalctl -p 3 -xb
jul 07 09:48:41 debian kernel: x86/cpu: SGX disabled by BIOS.
jul 07 09:48:42 debian kernel: nouveau 0000:01:00.0: bus: MMIO read of 00000000 FAULT at 6013d4 [ PRI>
jul 07 09:48:42 debian systemd[1]: Failed to activate swap dev-disk-by\x2duuid-1fdb2359\x2d6a76\x2d44>
░░ Subject: A unidade dev-disk-by\x2duuid-1fdb2359\x2d6a76\x2d44dc\x2db04f\x2da711cb5ad70a.swap falhou
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A unidade dev-disk-by\x2duuid-1fdb2359\x2d6a76\x2d44dc\x2db04f\x2da711cb5ad70a.swap falhou.
░░ 
░░ O resultado é failed.
```

I don't know how to fix this and if it's possible at this stage to do that.

```
root@debian:~# cat /etc/fstab 
UUID=ae5ec66f-a635-4d8f-ab0a-d6666c1f1669 / btrfs rw,noatime,compress=lzo,ssd,space_cache=v2,subvolid=256,subvol=/@ 0 0
UUID=ae5ec66f-a635-4d8f-ab0a-d6666c1f1669 /home btrfs rw,noatime,compress=lzo,ssd,space_cache=v2,subvolid=257,subvol=/@home 0 0
UUID=ae5ec66f-a635-4d8f-ab0a-d6666c1f1669 /.snapshots btrfs rw,noatime,compress=lzo,ssd,space_cache=v2,subvolid=258,subvol=/@snapshots 0 0
UUID=3a4efc74-4a65-45b2-bc8f-8997acd996ae /boot ext2 rw,relatime 0 0
UUID=3FE9-5C88 /boot/efi vfat rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro 0 0
tmpfs /tmp tmpfs rw,nosuid,nodev,inode64 0 0
UUID=1fdb2359-6a76-44dc-b04f-a711cb5ad70a swap swap defaults 0 0
```
```
root@debian:~# blkid
/dev/nvme0n1p1: UUID="1c8fa69e-6fa3-4c1d-907f-404e30c87012" TYPE="crypto_LUKS" PARTUUID="e559cc5c-8946-d74e-be4a-a6e24d6ef79a"
/dev/nvme0n1p2: UUID="1fdb2359-6a76-44dc-b04f-a711cb5ad70a" TYPE="crypto_LUKS" PARTUUID="577099ad-6f00-1448-96b7-016c5e12b22c"
/dev/mapper/cryptroot: UUID="ae5ec66f-a635-4d8f-ab0a-d6666c1f1669" UUID_SUB="006b15fa-d826-4c6f-a232-9f2bfdd055df" BLOCK_SIZE="4096" TYPE="btrfs"
/dev/sda2: UUID="3a4efc74-4a65-45b2-bc8f-8997acd996ae" BLOCK_SIZE="1024" TYPE="ext2" PARTUUID="71bc051d-d23c-a746-a218-74ffdb51fd10"
/dev/sda1: SEC_TYPE="msdos" UUID="3FE9-5C88" BLOCK_SIZE="512" TYPE="vfat" PARTUUID="6ad43b8a-51e7-464a-8db2-ee224515bac1"
```

Other considerations (noob questions):
• 1. Why do you install NetworkManager instead of Connman?
• 2. Do you think I can put grub boot time =0 ? Will I have trouble doing any system maintenance?
• 3. Don't you think it's better to create an LUKS over LVM, with just one password, for both partitions?
• 4. Should I  install plymouth screen ?

Interesting references:
[Full disk encryption (including boot) on Debian Bookworm](https://www.dwarmstrong.org/fde-debian/)
[Installing Debian 11 with btrfs Subvolumes on LUKS - blackpine.io](https://blackpine.io/posts/2022.04.14-installing-debian-11-with-btrfs-subvolumes-on-luks/)
[How to install Arch Linux with Encryption and a Swapfile](https://www.youtube.com/watch?v=OnqkksPUpsc)
[Debian Bullseye install with BTRFS Subvolumes](https://www.youtube.com/watch?v=TKK1YYF2Pro)
[Installing Debian Linux with full-disk encryption and a key-boot disk (Intro)
](https://www.youtube.com/watch?v=h_-19EyKdLs)

*Suggestion, in a next tutorial, could be made more didactic and include basic packages for the installation:
apt install cryptsetup-initramfs
apt install firmware-linux
apt install plymouth-x11

**THANKS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!**

**Comment by aomgiwjc** [comment]
Wow, OK, you seem pretty capable in regards to this one. I'm pretty close to a newbie myself for this, and this is an adapted method I was working on to show that it was possible for Debian. That said, it's flawed, and I tried to take it down but others demanded I leave it back up.

Some Google searching shows we may need the "mkswap" command on /dev/mapper/cryptswap. Then try the UUID for /dev/mapper/cryptswap.

**Comment by RENANZG** [comment]
It's very tiring, I'll go back to my old system kkkk.
This is interesting:
[Installation guide for Void Linux with LUKS-encrypted btrfs root](https://gist.github.com/gbrlsnchs/9c9dc55cd0beb26e141ee3ea59f26e21)

Thanks

**Comment by RENANZG** [comment]
I got it!

```
user@debian:~$ lsblk
NAME                  MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
sda                     8:0    1 116,1G  0 disk  
└─sda1                  8:1    1    40G  0 part  
  └─sdb1_crypt        253:0    0  39,9G  0 crypt 
    ├─debian--vg-root 253:1    0    34G  0 lvm   /home
    │                                            /.snapshots
    │                                            /
    └─debian--vg-swap 253:2    0   5,9G  0 lvm   [SWAP]
sdc                     8:32   1   480M  0 disk  
├─sdc1                  8:33   1   100M  0 part  /boot/efi
└─sdc2                  8:34   1   378M  0 part  /boot

```
The secret of the LVM of Calamares:
`mount /dev/mapper/ventoy  /cdrom`

I started partitioning in Live's Install Advanced mode (I think NetInstall would be better with Debian 12 non-free).  And I used three tutorials in this order:

1. Installing Debian Linux with full-disk encryption and a key-boot disk 
 https://www.youtube.com/watch?v=h_-19EyKdLs

2. Debian Bullseye install with BTRFS Subvolumes
https://www.youtube.com/watch?v=TKK1YYF2Pro

3. Debian 11.5 BTRFS and Luks Encryption Installation 
https://www.youtube.com/watch?v=9ia0Nhk3mFo

Thanks
